apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-shop3
  namespace: microservice-shop3
  labels:
    app.kubernetes.io/name: microservice-shop3
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-shop3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice-shop3
    spec:
      containers:
        - name: microservice-shop3
          image: ccr.ccs.tencentyun.com/mandala/microservice-shop:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Namespace
metadata:
  name: microservice-shop3
