apiVersion: v1
kind: Service
metadata:
  name: microservice-shop3
  namespace: microservice-shop3
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: microservice-shop3
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31040
