apiVersion: argoproj.io/v1alpha1 # 指定 Argo CD API 版本
kind: Application # 定义资源类型为 Application
metadata: # 元数据部分
  name: e-commence # 指定 Application 的名称
  namespace: argocd # argocd所在的命名空间
  # # 定义资源的 finalizers
  # https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/#about-the-deletion-finalizer
  finalizers:
    # - resources-finalizer.argocd.argoproj.io # 删除时行级联删除
    - resources-finalizer.argocd.argoproj.io/background  # 删除时后台行级联删除
spec: # 规范部分
  project: tiktok-e-commence # 应用程序将被配置的项目名称，这是在 Argo CD 中应用程序的一种组织方式
  source: # 指定源
    # Kubernetes 资源清单在仓库中的路径
    path: user/manifests/application/overlays/production
    # 从 Helm 存储库创建应用程序时，必须指定 chart 属性，而不是 spec.source 中的 path 属性
    # chart: argo
    # 指定 Git 仓库的 URL
    repoURL: https://github.com/sunmery/tiktok_e-commence.git
    # targetRevision：想要使用的 git 分支
    targetRevision: pre
  # Kubernetes 集群中的目标
  destination:
    namespace: tiktok # 指定目标命名空间
    server: https://10.0.1.3:6443 # 指定目标服务器
  syncPolicy: # 指定同步策略
    automated: # 自动化同步
      prune: true # 启用资源清理
      selfHeal: true # 启用自愈功能
      allowEmpty: false # 禁止空资源
    syncOptions: # 同步选项
      - Validate=true # 禁用验证
    retry: # 重试策略
      limit: 5 # 重试次数上限
      backoff: # 重试间隔
        duration: 5s # 初始重试间隔
        factor: 2 # 重试间隔
        maxDuration: 3m # 最大重试间隔
